### ISSUE TITLE
 Martingale betting system

### ISSUE THREAD

**Issue by Yishaqel** [Tkd-Alex/Twitch-Channel-Points-Miner-v2#17]
In roulette, starting with a fixed amount of money and progressively betting that amount you can win money, if you lose then double that bet amount to recover what you have lost.

The point is that it could be implemented in some way to bet on this program, to try to maintain a betting logic that generally works quite well.

My english is fairly limited and maybe someone has more knowledge to explain what I am trying to do. In roulette there are three options to bet and two of those options return 50% of what you bet, so maybe you have to do something else because of the variable percentages of the twitch bets.

**Comment by Tkd-Alex** [comment]
We need also math skills :laughing:

**Comment by testdev123456** [comment]
> We need also math skills

I don't think "Martingale" can be applied here because even if you win, sometimes you win a +2% of your bet... sometimes to only recover your bet when it's 50-50% -  It really depends on many factors your final 'point reward'.  Martingale works somewhat ok in games that give you a FIXED prize ( like doubling your bet if you played 'black or red' in Roulette ) .  
So.. Martingale here would be catastrophic!

**Comment by testdev123456** [comment]
i think we can close this..
