### ISSUE TITLE
auto crash at startup

### ISSUE THREAD

**Issue by vegych** [Tkd-Alex/Twitch-Channel-Points-Miner-v2#179]
I use a program for Windows and decided to try it on Linux (twister os)
After running on Linux, the window closes and it says
Traceback (most recent call last):
File /home/pi/Twitch-Channel-Points-Miner-v2/run.py", line 4, in <module>
from colorama import Fore
ModuleNotFoundError: No module named 'colorama'.
Searching for instructions and questions did not give an answer. How can the problem be solved?

**Comment by RakSrinaNa** [comment]
Answer is in the readme. (Section 'how to use' (2nd point))

**Comment by vegych** [comment]
pip install virtualenv
virtualenv -p python3 venv
source venv/bin/activate
pip install -r requirements.txt
Do I understand correctly that after the first command I need to open the command line from under the folder with the bot and write the next one there. I did this, but at the last stage, for some reason, it looks for the .txt file, but does not give requirements.
This is my first experience with Linux. So maybe I'm doing something wrong

**Comment by RakSrinaNa** [comment]
This shouldn't really differ from windows if you're going through the terminal. All the commands need to be executed from the root folder of the project (the folder you clone).

For the venv you're not forced to use it. You can also skip it and use the python that comes with your distro (that's what I personally do).
Though be careful, sometimes `python` points to a Python 2 installation and you need to use `python3`/`pip3` instead. (you can check with `python -v`).

**Comment by vegych** [comment]
did everything as you said and still have the same error:(

**Comment by RakSrinaNa** [comment]
* How do you start the script?
* What version of python does that correspond to?
* How did you install dependencies?

**Comment by vegych** [comment]
recorded a video
https://drive.google.com/file/d/1LQXllcRfebwM9WhLy8071xAUmKtIN_5U/view?usp=sharing

**Comment by RakSrinaNa** [comment]
You can't just run the file by double clicking it.

What you're doing here is install all the dependencies in a virtual python environment (you activate it with `source venv/bin/activate` and you see the `(venv)` in your terminal after). But when you double click the py file you don't start it in a virtual env.

You need to start your script from the terminal.

```bash
source venv/bin/activate
python run.py
```

**Comment by vegych** [comment]
Thank you, now I understand what my mistake was)

**Comment by RakSrinaNa** [comment]
Just to be clear, when I posted the commands, they do different things.

```bash
git clone https://github.com/Tkd-Alex/Twitch-Channel-Points-Miner-v2
cd Twitch-Channel-Points-Miner-v2
pip3 install -r requirements.txt
```
Clones the project and install the dependencies in you ENVIRONMENT PYTHON 3.


```bash
git clone https://github.com/Tkd-Alex/Twitch-Channel-Points-Miner-v2
cd Twitch-Channel-Points-Miner-v2
pip install virtualenv
virtualenv -p python3 venv
source venv/bin/activate
pip install -r requirements.txt
```
Clones the project, create a VIRTUAL PYTHON ENVIRONMENT, and install the dependencies in it.

You have to choose either one of them but not both.

In the first case you'd start the script with `python3 run.py`. In the second case with 
```
source venv/bin/activate
python run.py
```

Also if you look closely when you double click the file it starts a Python 2.7 install. This is what I mentioned in https://github.com/Tkd-Alex/Twitch-Channel-Points-Miner-v2/issues/179#issuecomment-841627928 , linux env often have both python2 and python3 installed. If you want to be able to run it by double clicking you'll need to find by yourself how to change in your OS what happens when you double click a file and make it use python3 instead of python2.
