### ISSUE TITLE
Request: User interface

### ISSUE THREAD

**Issue by Der-Floh** [Tkd-Alex/Twitch-Channel-Points-Miner-v2#234]
**Making a working UI would be the tip of the iceberg and ofcourse not easy to accomplish**

But if we had a working UI with the logs and some buttons like "manage Streamers" where you can add or remove streamers the whole program would be much easier to use. 
Then you wouldn't have to edit the run.py file each time.
This would be, espacially for new Users or people who generally don't have much knowledge on pc / python stuff, way easier to use

You could even integrate the analytics in the ui (if its possible I don't have much knowledge of python 😅 )

Just wanted to suggest that cause having this programm beeing a really good application and great to use is the goal right ? 
So I'm doin my best to help accomplishing that 🥰

**Comment by ceoshikhar** [comment]
@IDerFlohI Hey 👋

Around one and a half month ago, I came up with the thought of trying to make an app that will farm channel points for me. Mainly because the streamers I watch are from NA and I am from India, so it's really hard for me to watch them online. Hence I always had low channel points. I also love to *gamba* channel points in chat predictions. 

As I started working on my project, I came across https://github.com/gottagofaster236/Twitch-Channel-Points-Miner which led me to this repository. I also came across this issue created by you.  So I decided to make a GUI App that will do the basic things at least (farm channel points for a list of streamers) and hopefully build more features.

Today, after more than a month later, I have release the first version of the app. I called it Twester ( Twitch Harvester ). It's heavily inspired by this project and the original repo. I have no experience with Python but I do have with JavaScript. So I did what I could.

[Twester](https://github.com/twesterapp/twester) is a desktop app created with `React`, `Electron` and `Node.js`. I am not sure if you would love it, but it's something towards what you mentioned in the description of the issue.

Thanks for reading! I hope this helps someone. Once again, thanks to @Tkd-Alex for this amazing repo. I couldn't have made Twester without this. ♥
