### ISSUE TITLE
Got Termux to work but now i face this https problem

### ISSUE THREAD

**Issue by Galaxtxc** [Tkd-Alex/Twitch-Channel-Points-Miner-v2#275]
**Desktop (please complete the following information):**
 - OS: [Termux]
 - Python version [ 3.9.7]

I literally have no clue how to fix this as i am new to this
![Screenshot_20210915-025827~2](https://user-images.githubusercontent.com/90735674/133353721-48f6da6b-0842-4862-90ce-82c3dadaa1fb.png)

**Comment by Galaxtxc** [comment]
It seems this occurs everytime the script tries to collect channel points.

**Comment by RakSrinaNa** [comment]
It's a connectivity/network issue. Twitch website can't be reached.

**Comment by Galaxtxc** [comment]
Do you know any fix i could apply to get a workaround ?

**Comment by RakSrinaNa** [comment]
That will depend on your OS. You'll have to find a way to make it reach the URL that is in the logs.
Seeing it says "No address associated" it seems like a DNS issue to me.

So either it continues in time and you'll probably have to change settings on your device. Or it's temporary and it was an issue on the DNS side.

**Comment by Galaxtxc** [comment]
Okay right now i disabled Wifi and VPN and it seems to work. Because of this ill close this thread for now, thanks for the answer.

**Comment by MaciejGorczyca** [comment]
I just wanted to add that I used Twitch-Miner in Docker for Windows with WSL2 and had some issues too. About 3/4 of the requests were fine but 1/4 of them would throw the following error:


`16/09/21 09:18:36 - ERROR - [send_minute_watched_events]: Error while trying to send minute watched: HTTPSConnectionPool(host='video-edge-a8d08c.pdx01.abs.hls.ttvnw.net', port=443): Max retries exceeded with url: /v1/segment/ChkxqF3v6FBcvMuLpEl4JWMaFN4t1uvFZVERC8_KQoBzWe_opsIZwqsvuSIekDyftgB5QovvP50_YIIdt9xCRRczjvJmw1O_zEk-gv4e5zBtTjc73-4AjrYKLQAZK5nrg5w_niwiMpVFtUbpBnSfQ_jV57mMcAY3OKd9J9xgCxkCJpFXZzgVjPaUGICHSKHt4gLvSZIqJ1quf2m9AzXf4ouOn2wCc1hN0ImI7BH0igHdK8L0cPl_qfX8QhuMeJDCR54AwPksnjvUN3cKmS060BHmloRNh-8XaJeD9fQawX90dhVeXcAN-rrnt2UwuotHTbjDtYPr8I7hr0RvlCJ4JoDV8vq92u7nHAIYc-BRbWL_RE5DvZUuX4iwBwudzlGlYSneIdfA01PhHsp_E2LaojfS9ZewN4V8VlcVLd7FsLpyVhw3S8CxicjnMuKhq5kslrHgbuXXUGNSyKmvkxSCB0X4-hfgX-iKVqzxGIgyB-mv-Xp3afbXOB-_6Q9xrssLPTn0hj68mob6UDZCJcJ6HdUZc1A85Di29-6QZ-j1vADlRnNr-huztEoxkLf_iQIIkbVT7CkIeUYktNBmPOEG5SYgjBCk3ou5xdKPA01sMtG6RG-pQkVLbS7pZ8cF6VhY3KnOLiqYJczChB6vLO4RQtWuZqq1HaXn0tZFgC3zq1oOLH0CveMUT9kXgfrnQyx-6CVlzLqOQ_zht1X3b8ReU0b_DborHvqXlVWjcX_91a9-mrNzJEu3CWLHO0X6fXIdWBL8.ts (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f449fce6910>: Failed to establish a new connection: [Errno -5] No address associated with hostname'))`

Turns out adding a bunch of DNS fixed the issue. Added like 6 DNS servers and didn't get the problem anymore.
