### ISSUE TITLE
Queued betting

### ISSUE THREAD

**Issue by SiIason** [Tkd-Alex/Twitch-Channel-Points-Miner-v2#28]
Currently you can not bet on a second bet until the initial closes/completes.

Is it possible to put all betting opportunities into a holding list.
Stay focused on one bet until the bet is made ~90 seconds (then hand it off for another process to deal with completion).
Take the next oldest betting opportunity from the holding list and check if it's newer than 90seconds (current bet wait time)
If newer than 90s then wait for prediction time to pass to 90s and place bet, else drop bet as missed.
(repeat until list empty)

This would mean splitting the information collection of finished bets to a separate check/thread (if it isn't already)
No interaction is required this is for user feedback report only.

**Comment by Tkd-Alex** [comment]
This can be handling multiple problems.
The prediction windows It's not always 90 seconds, but can be dynamic. 

How many times you got multiple bet simultaneously? I think It's really rare that It's happened.
I don't think I'll work on a queue system for the bet, but we can try to execute the methods 
https://github.com/Tkd-Alex/Twitch-Channel-Points-Miner-v2/blob/3357c3b6daa2f59c1a7619e23797bb3f4002fba5/TwitchChannelPointsMiner/classes/TwitchBrowser.py#L267
https://github.com/Tkd-Alex/Twitch-Channel-Points-Miner-v2/blob/3357c3b6daa2f59c1a7619e23797bb3f4002fba5/TwitchChannelPointsMiner/classes/TwitchBrowser.py#L302

One after the other, instead of the current system:
1. `start_bet`
2. `wait x seconds`
3. `place_bet`

And see if it works

**Comment by SiIason** [comment]
As far as how often does this happen, I agree normally its rare.
however during events and the like I noticed it common for multiple streams to run prediction bets, and this is where I've noticed the issue.
