### ISSUE TITLE
Limit betting by participation

### ISSUE THREAD

**Issue by SiIason** [Tkd-Alex/Twitch-Channel-Points-Miner-v2#29]
Would like to see an option to limit betting on votes with a small amount of participants.

So we could choose not to bet on votes involving less than 20 people for example.

**Comment by testdev123456** [comment]
Since we're improving predictions, I would also like to see:

An **option to bet 1 point less than the current highest bet**.  I'll explain:

The prediction box, shows the username of the highest bet from OptionA and OptionB.  So, in a small channel, where sometimes everyone knows each other.. If we show up as the highest bet all the time... and don't even talk.. we would raise suspicion. Plus, since we don't show up in the user-list..  they would freak out even more..!

So my suggestion is..  that at the moment we're about to place our bet to Option2 for example....  check the amount of the highest bet from Option2 and place the bet just 1 point less of it.. and continue to be 'hidden' from chat.  

Of course, that value will continue to obey and be within:  `bet_settings=BetSettings(percentage=5,max_points=50000)`
if it's an option in run.py .. .we could call it `stealth_mode=True`

**Comment by Tkd-Alex** [comment]
> Would like to see an option to limit betting on votes with a small amount of participants.
> 
> So we could choose not to bet on votes involving less than 20 people for example.

We should create a `FILTER` mode for prediction. Nice idea :100:

**Comment by Tkd-Alex** [comment]
@testdev123456 Please open another Issue for the `stealth_mode`. The main idea of this Issue are different from yours
