### ISSUE TITLE
cleaning analytics every month

### ISSUE THREAD

**Issue by Michael1297** [Tkd-Alex/Twitch-Channel-Points-Miner-v2#316]
after about 1-2 months, the site with analytics starts lagging and I have to manually delete all analytics

**Comment by Tkd-Alex** [comment]
@Michael1297 can you test the #131 please?

**Comment by Michael1297** [comment]
tested https://github.com/Tkd-Alex/Twitch-Channel-Points-Miner-v2/pull/131
Showing weekly analytics does not cause lags(~2000 elements)✔️
Showing monthly analytics causes lags(~11000 elements)❌

I propose to set a limit of 5000 elements and when this limit is reached, when adding a new element, delete the old element.

**Comment by Tkd-Alex** [comment]
Lags also without annotations?

**Comment by Michael1297** [comment]
https://user-images.githubusercontent.com/38764610/141123080-8c53a067-1a0f-41a3-8f97-c5fa14e49efb.mp4

**Comment by RakSrinaNa** [comment]
Doing a date range is nice to exclude some part of the data, but to me it doesn't fixe the issue. If you wanna see the graph of the last year of data and got a streamer that streams every day.... you'll get a ton of points. 

With the date range we're basically reducing the number of points by removing a whole range from the total. But IMO what would be better is to aggregate the data at some point. That way we can still see data over extended period of time instead of being limited to a relatively small time range.

Like for example a threshold of let's say there's a 10k point limit that is defined. If there's 9k points then display them all, but if there's more then aggregate them to be under that threshold. If there are 15k points in total then we could return every other points (we keep a point every `ceil(15000/10000)` "scanned), and so instead of having 15k you'd have 7.5k.
Of course there may be special treatment for some points. Like predictions, they don't happen that often and give valuable info, so maybe should skip them all. But the +10 points that happen every 5 minutes... honestly it's fine if over a large period you get it every 30mins and so jumps by 60 points.

In my case, I have the analytics data since around the beginning it was introduced, but it's simply unusable.
If we're forced to define a time range that can't be more than x days, then better delete that data entirely from the JSON file to save space on disk.

**Comment by Tkd-Alex** [comment]
This could help also to improve the performance
https://github.com/apexcharts/vue-apexcharts/issues/208#issuecomment-591571907

**Comment by Tkd-Alex** [comment]
@Michael1297 It's a problem for you to zip and send via mail all your analytics?

**Comment by Michael1297** [comment]
@Tkd-Alex 
[analytics.zip](https://github.com/Tkd-Alex/Twitch-Channel-Points-Miner-v2/files/7513443/analytics.zip)

after downloading the file, delete this message

**Comment by Tkd-Alex** [comment]
The latest commit should be a valid fix :)
https://github.com/Tkd-Alex/Twitch-Channel-Points-Miner-v2/pull/131/commits/5906f210273690fde8febbe59ad37587528657a7

**Comment by Michael1297** [comment]
> The latest commit should be a valid fix :)

Thanks a lot.
