### ISSUE TITLE
Betting strategy: Follow most trustworthy users.

### ISSUE THREAD

**Issue by 15sawyer** [Tkd-Alex/Twitch-Channel-Points-Miner-v2#359]
I was thinking about the possibility to place a bet that follows the most trustworthy users. What do I mean? 
In Twitch chat, you can see what other users voted. Some users are better at betting than others (assuming we don't deal with a 100% randomized subject). This is why it would be great to analyze what users bet and weigh them, according to their success rate. This weight could then be used to make a more accurate betting strategy. 

**Requirements:**
* A way to extract the chosen option per user/chat message.
* A lightweight DB to save the past data.

I would create a PR myself, but since I have no experience with twitch bots, I wanted to ask if this is feasible first. Especially the part where we extract the chosen option from the chat messages. 

**Edit:**
I created a chatbot and checked the available parameters. It gives something like: "badge-info":{"predictions":"Prediction1"}.
So this should absolutely be possible.

**Comment by 1v** [comment]
But how do you know this user is best? Collect data for each user in chat? I think this is out of scope from this project.
I can tell you that top points gainers is top because they bet many points and/or they bet frequently. So more successful and less frequent betters have big gains but not enough to overcome frequent betters.

**Comment by byaura** [comment]
This would be great! Please do it.
