### ISSUE TITLE
Error with GQLOperations (VideoPlayerStreamInfoOverlayChannel)

### ISSUE THREAD

**Issue by haleypadawan** [Tkd-Alex/Twitch-Channel-Points-Miner-v2#383]
Error "Error with GQLOperations (VideoPlayerStreamInfoOverlayChannel)" keeps being displayed on the console while its running. I noticed the one im using is having random errors so i tried restarting it then it stopped working. I decided to make a new copy by cloning this github and making a new run.py using the new example.py and now theres this error. I made sure to do "pip install -r requirements.txt" to make sure all the requirements are downloaded and/or updated.

P.S: Theres also a new error message at the very beginning of running the script "Unable to detect if you have the latest version of this script". Also theres this weird error that says some of my twitch streamer doesnt exist even tho they clearly do and I didnt have this issue last time.

 - OS: Windows 10
 - Python version 3.9

I'll upload the log and my run.py/run.txt
[twitchminer.log](https://github.com/Tkd-Alex/Twitch-Channel-Points-Miner-v2/files/7820765/twitchminer.log)
[run.txt](https://github.com/Tkd-Alex/Twitch-Channel-Points-Miner-v2/files/7820770/run.txt)

**Comment by Tkd-Alex** [comment]
`06/01/22 16:45:20 - ERROR - TwitchChannelPointsMiner.classes.Twitch - [post_gql_request]: Error with GQLOperations (ChannelFollows): HTTPSConnectionPool(host='gql.twitch.tv', port=443): Max retries exceeded with url: /gql (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x0000026CADA9B9A0>: Failed to establish a new connection: [WinError 10060] A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond'))`

It's just a connection issue

**Comment by haleypadawan** [comment]
Thanks! It looks like it is just yesterday issue which might just be the connection as mentioned. This can be closed now.
