### ISSUE TITLE
Discussions & PRs

### ISSUE THREAD

**Issue by RakSrinaNa** [Tkd-Alex/Twitch-Channel-Points-Miner-v2#48]
This isn't an issue for the bot itself but for the repo.

I have 2 suggestions:
* It'd be cool to enable the `Discussion` tab in the repo. Just like you did for the issues at the beginning, you could enable the discussions so that people that just have little questions or other discussions that are not issues can exchange about the topic.
* Would be nice if PRs are used a bit more. Maybe even make it a workflow by always attaching a PR to an issue.
Currently there's a lot of branches and it's a bit hard to track a bit all that's going around. 
Having PR would allow you to link the PR to the issue so the changes for an issue are somehow "logged" and can be found at a later date a bit more easily. 
Also people that reported issues could subscribe to the PR and get notifications when changes are made. 
Finally it would be easier to suggest changes. I did it a few times directly in the commits but it's not really that visible to others that could also have suggestions.

**Comment by Tkd-Alex** [comment]
- I've manually disabled the discussion tab a few days ago. Personally I don't really like this feature, because a new user maybe can be a bit confused where to write his question or suggest new feature. In this way we have only the Issue tab and I've solved the problem 😂 But if you say that can be helpful in the future I'll enable again
- The workflow that you are suggesting It's the same that I am currently using. The master branch should be the stable branch. If there is a hot-fix or little changes ans I'm sure that wont break anything I push in the master branch. When a user suggest a new feature or the bug It's a quiet big I work on separate branch e once It's fully working and tested I make and merge the PR (with linked issue) - as you can see for the example in the actually closed PRs (for example the watch-time for drop inventory). Maybe you would suggest to create a draft of the PR? 

btw, today I think I'll create a PRs for all branches an merge everything into master 💣

**Comment by RakSrinaNa** [comment]
* It can stay that way too. As you say the feature is rather new and can confuse some people.
* Yeah it is fine as it is. Maybe I didn't really used the correct word with the `workflow`. For small features/fixes doing it directly in master makes sense of course. What I meant was to to open the PRs at the beginning of the work. Not just at the end when it's going to be merged. Just so that people that report issues can follow a bit what's happening if they want, and people more into code can also give feedback on it. Seeing what is being committed across branches isn't really easy in GitHub.
