### ISSUE TITLE
init() got an unexpected keyword argument 'key' + Windows issue

### ISSUE THREAD

**Issue by papiLUL** [Tkd-Alex/Twitch-Channel-Points-Miner-v2#55]
I'm getting this message when I play the code 
__init__() got an unexpected keyword argument 'key'

**Comment by Tkd-Alex** [comment]
Share s screenshot or full error logs

**Comment by papiLUL** [comment]
http://prntscr.com/yk2an3

**Comment by RakSrinaNa** [comment]
In `FilterCondition`, replace `key` with `by`.

https://discord.com/channels/432623139885940738/432623140498178051/807273963683053618

**Comment by Tkd-Alex** [comment]
use `by` instead `key`, I forgot to update the example file

**Comment by RakSrinaNa** [comment]
@Tkd-Alex Also in the readme, there's "Allowed values for `key` are:"

**Comment by papiLUL** [comment]
it works now but only in pycham 
in python it won't run
https://www.youtube.com/watch?v=PJiqtfmFoqE&ab_channel=Mat%C4%9BjPap%C3%A1%C4%8Dek

**Comment by RakSrinaNa** [comment]
Probably that PyCharm is ran as an administrator but not when you do from the explorer.

You should probably run the script from a terminal instead of from the explorer so you can see the error: `PermissionError: [WinError 5] Pristup bys odepren: C:/WINDOWS/System32/Cookies`.
This is due to the fact that when you run the file that way, it's working directory is `C:/WINDOWS/System32` and not your current directory.

**Comment by papiLUL** [comment]
I managed to run it in cmd
how do I run it in python?

**Comment by RakSrinaNa** [comment]
`python run.py`

Or you can copy the command that pycharm runs and that is displayed at the beginning of a run.

**Comment by papiLUL** [comment]
it's all working now 
thank you so much  <3
