### ISSUE TITLE
Doesnt collecting channel bonus

### ISSUE THREAD

**Issue by taurynamonsterxdd** [Tkd-Alex/Twitch-Channel-Points-Miner-v2#614]
Miner doesnt collect channel points
HEROKU

**Comment by rdavydov** [comment]
Duplicate of https://github.com/Tkd-Alex/Twitch-Channel-Points-Miner-v2/issues/592, as well as part of https://github.com/Tkd-Alex/Twitch-Channel-Points-Miner-v2/pull/594.

**Comment by taurynamonsterxdd** [comment]
@rdavydov  doesnt work xdd

**Comment by mtrcode** [comment]
yeap, me too :c
author is supporting this project yet?

**Comment by rdavydov** [comment]
> @rdavydov doesnt work xdd
> yeap, me too :c author is supporting this project yet?

This problem is already known and documented in a previously opened issue. You have to read and search before you open a new one. We don't want a pile of duplicate issues.

Author doesn't currently support this project. See https://github.com/Tkd-Alex/Twitch-Channel-Points-Miner-v2/pull/594#issuecomment-1247863704

**Comment by rdavydov** [comment]
Quickly implemented the workaround kindly shared by @6accOnThe6locc

Code https://github.com/rdavydov/Twitch-Channel-Points-Miner-v2/tree/workaround

For noobs ;) https://github.com/rdavydov/Twitch-Channel-Points-Miner-v2/releases/tag/0.1

P.S. Delete your old cookie file(s) cookies/*.pkl and authenticate again.

**Comment by taurynamonsterxdd** [comment]
@rdavydov yea its work <3 ty man

**Comment by kapiorr** [comment]
great work TY :D
