### ISSUE TITLE
All predictions show status as "LOCKED"

### ISSUE THREAD

**Issue by BarkerB** [Tkd-Alex/Twitch-Channel-Points-Miner-v2#83]
I've been using this tool for the past few days and it has been working really well. Today I noticed it wasn't participating in predictions and so I went and looked at the log and noticed all of my recent predictions had a status of LOCKED and my account didn't participate in them.

Is this something like a soft-ban from Twitch? Or is this related to this tool? I couldn't find any information on what the different statuses mean, maybe it would be good if we could add them to the README.

Thanks for the help!

(Example prediction, some information redacted for safety :) )
```
20/02/21 10:20:20 - INFO - TwitchChannelPointsMiner.classes.Twitch - [make_predictions]: 🍀  Going to complete bet for EventPrediction(event_id=****, streamer=Streamer(username=****, channel_id=***, channel_points=***k), title=Will they win?)
20/02/21 10:20:20 - INFO - TwitchChannelPointsMiner.classes.Twitch - [make_predictions]: 😥  Oh no! The event is not active anymore! Current status: LOCKED

```

**Comment by Tkd-Alex** [comment]
No, I don't think It's a soft ban.
I had this message multiple times in the past and usually appear with the same streamer.

I think It's just because sometimes the moderator or owner "close" the prediction before It's time. The script was developed for place the bet just 3/4 seconds before It's finish but if someone close the bet before this time we are unable to place the bet.

**Comment by BarkerB** [comment]
Thank you for the reply! I was concerned because it was happening from multiple channels at the same time - but yes I think that was a coincidence. I started it up again shortly after making this post and everything is fine. Thank you! 😄
